### ISSUE TITLE
Gives array end limits for extrapolation.

### ISSUE THREAD

**Issue by saisankargochhayat** [likr/spline-interpolator#1]
If the value is out of range it doesn't provide the extrapolation value. Can someone please implement this ?

**Comment by likr** [comment]
Hi, I have implemented the extrapolation feature.
See: https://github.com/likr/spline-interpolator/tree/extrapolation
Is this your expected behavior?

I'll release v1.0.0 because this causes breaking changes.

**Comment by saisankargochhayat** [comment]
This seems to work fine :smile: Should i add a test case ?

**Comment by likr** [comment]
I have released v1.0.0.
The test case is not necessary, but, I'll merge if you send PR.
